<a href="https://colab.research.google.com/github/apalyukha/colab_samples/blob/main/sample.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys

In [2]:
print(sys.version)

3.7.10 (default, May  3 2021, 02:48:31)
[GCC 7.5.0]

In [3]:
import pandas as pd

In [4]:
df = pd.DataFrame([('Foreign Cinema', 'Restaurant', 289.0),
                   ('Liho Liho', 'Restaurant', 224.0),
                   ('500 Club', 'bar', 80.5),
                   ('The Square', 'bar', 25.30),
                   ('Page', 'bar', 80.34),
                   ('Tompkins', 'bar', 34.2),
                   ('Als Place', 'Restaurant', 56.52),],
           columns=('name', 'type', 'AvgBill')
                 )
df

             name        type  AvgBill
0  Foreign Cinema  Restaurant   289.00
1       Liho Liho  Restaurant   224.00
2        500 Club         bar    80.50
3      The Square         bar    25.30
4            Page         bar    80.34
5        Tompkins         bar    34.20
6       Als Place  Restaurant    56.52

In [5]:
df.sample(n=2)

         name type  AvgBill
3  The Square  bar     25.3
5    Tompkins  bar     34.2

In [6]:
df.sample(n=5, replace=True)

             name        type  AvgBill
3      The Square         bar    25.30
0  Foreign Cinema  Restaurant   289.00
5        Tompkins         bar    34.20
4            Page         bar    80.34
4            Page         bar    80.34

In [7]:
import requests

In [8]:
requests.get('https://api.github.com')